# Generated by Django 5.1.5 on 2025-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chat_dim_onboarding_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_dim_onboarding_questions',
            name='order',
            field=models.IntegerField(),
        ),
    ]
