# Generated by Django 5.1.5 on 2025-02-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chat_dim_onboarding_questions_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_question_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='chat_facts_onboarding_answers',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='chat_dim_onboarding_options_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chat_dim_onboarding_questions')),
            ],
        ),
        migrations.AddField(
            model_name='chat_dim_onboarding_questions',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dim_question_type'),
        ),
    ]
