# Generated by Django 5.1.5 on 2025-02-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dim_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_dim_onboarding_options_answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.chat_dim_onboarding_questions'),
        ),
    ]
