# Generated by Django 5.1.5 on 2025-03-30 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_diary_facts_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_dim_onboarding_options_answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_options', to='api.chat_dim_onboarding_questions'),
        ),
        migrations.AlterField(
            model_name='chat_dim_onboarding_questions',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_question_types', to='api.dim_question_type'),
        ),
        migrations.AlterField(
            model_name='chat_facts_onboarding_answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_answers', to='api.chat_dim_onboarding_questions'),
        ),
        migrations.CreateModel(
            name='dim_am_i_boring_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('order', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boring_question_types', to='api.dim_question_type')),
            ],
        ),
        migrations.CreateModel(
            name='dim_am_i_boring_options_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boring_options', to='api.dim_am_i_boring_questions')),
            ],
        ),
        migrations.CreateModel(
            name='facts_am_i_boring_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boring_answers', to='api.dim_am_i_boring_questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
