# Generated by Django 5.1.5 on 2025-04-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chat_facts_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_facts_feedback',
            name='bot_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chat_facts_feedback',
            name='user_prompt',
            field=models.TextField(),
        ),
    ]
