# Generated by Django 5.1.5 on 2025-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_chat_facts_feedback_bot_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_memories',
            name='user_message_sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
