# Generated by Django 5.1.5 on 2025-05-23 03:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chat_memories_user_message_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_memories',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
