# Generated by Django 5.1.5 on 2025-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_facts_memos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts_memos',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
