# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Cloud Run Developer (roles/run.developer)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources
#
# 3. Change the values in the "env" block to match your values.

name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - "'main'"

env:
  PROJECT_ID: #'lulu-mvp' # TODO: update to your Google Cloud project ID
  REGION: #'europe-west3' # TODO: update to your region
  SERVICE: #'lulu-teaches'  # nome do serviço no Cloud Run
  REPOSITORY: #'happy-kids-backend'  # nome do repositório no Artifact Registry 
  WORKLOAD_IDENTITY_PROVIDER: #'projects/988538575854/locations/global/workloadIdentityPools/happy-kids-pool/providers/happy-kids-provider' # TODO: update to your workload identity provider
  SERVICE_ACCOUNT_EMAIL: #'lulu-auth-service@lulu-mvp.iam.gserviceaccount.com'
  GITHUB_AUDIENCE: #'https://github.com/MVP-Psicologia-Positiva/lulu-teaches-mvp'


jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4 # actions/checkout@v4

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2 #google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account:            '${{ env.SERVICE_ACCOUNT_EMAIL }}'
          audience:                   '${{ env.GITHUB_AUDIENCE }}'
          project_id:                 '${{ env.PROJECT_ID }}'
          token_format:               'access_token'
          scopes:                     'https://www.googleapis.com/auth/cloud-platform'
          export_default_credentials: true
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: 🔍 Debug GCP Auth
        run: |
          echo "**Conta ativa:**"
          gcloud auth list

      # BEGIN - Docker auth and build
      #
      # If you already have a container image, you can omit these steps.

      - name: Configure Docker to use gcloud credential helper
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      
      - name: 🔍 Check Artifact Registry IAM
        run: |
          gcloud artifacts repositories get-iam-policy ${{ env.REPOSITORY }} \
            --location=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --format="table(bindings.role, bindings.members)"

      - name: 'Build and Push Container'
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build -f happy-kids/Dockerfile -t "${DOCKER_TAG}" happy-kids/
          docker push "${DOCKER_TAG}"
        
      - name: 'Deploy to Cloud Run'

        # END - Docker auth and build

        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          # NOTE: If using a pre-built image, update the image name below:

          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}'
      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |2-

          echo ${{ steps.deploy.outputs.url }}